# Generated by Django 4.0.6 on 2022-07-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_tunedto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tunedto',
            name='date',
            field=models.DateField(verbose_name='Tuning Date'),
        ),
    ]
