# Generated by Django 4.0.6 on 2022-07-21 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_tunedto_tuning'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TunedTo',
            new_name='Tuned',
        ),
    ]
