# Generated by Django 4.0.6 on 2022-07-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_tunedto_tuned'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('band', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='tuned',
            options={'ordering': ['-date']},
        ),
    ]
