# Generated by Django 4.0.6 on 2022-07-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_player_alter_tuned_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='guitar',
            name='players',
            field=models.ManyToManyField(to='main_app.player'),
        ),
    ]
